# to delete old ./_site cache folder: bundle exec jekyll clean
# to build the site: bundle exec jekyll build
# to build the site as production: JEKYLL_ENV=production bundle exec jekyll build
# to view the site locally: bundle exec jekyll serve
# to view the site in realtime: bundle exec jekyll serve --livereload

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mito mapper
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/mito" # the subpath of your site, e.g. /blog
url: "https://snowxwang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
# theme: minima
plugins:
  - jekyll-feed

# Aux links for the upper right navigation
aux_links:
  "mito mapper on GitHub":
    - "//snowxwang.github.io/mito/"


# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
